# Generated by Django 5.2.7 on 2025-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_producto', models.PositiveIntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('id_expansion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Producto de Pokémon',
                'verbose_name_plural': 'Productos de Pokémon',
            },
        ),
    ]
